### ISSUE TITLE
test文件夹里的测试代码会报错。

### ISSUE THREAD

**Issue by CS-Jackson** [hey-yahei/OpSummary.MXNet#1]
具体错误代码如下，不知道你有没有遇到这种情况？

Traceback (most recent call last):
  File "/home/qbzhao/CSJ/Dettoolbox/test_flops.py", line 120, in <module>
    test_op_summary(mobilenet_v2_1_0, drop_fc=drop_fc)
  File "/home/qbzhao/CSJ/Dettoolbox/test_flops.py", line 77, in test_op_summary
    op_summary(net, (nd.ones(shape=input_size)), exclude=_fetch_dropped_fc(m, net) if drop_fc else [])
  File "/home/qbzhao/anaconda3/envs/gluon/lib/python3.6/site-packages/mxop/gluon/utils.py", line 78, in op_summary
    op_counter = count_ops(net, input_size, custom_ops, exclude)
  File "/home/qbzhao/anaconda3/envs/gluon/lib/python3.6/site-packages/mxop/gluon/utils.py", line 70, in count_ops
    __ = net(nd.zeros(shape=input_size))
  File "/home/qbzhao/anaconda3/envs/gluon/lib/python3.6/site-packages/mxnet/ndarray/utils.py", line 67, in zeros
    return _zeros_ndarray(shape, ctx, dtype, **kwargs)
  File "/home/qbzhao/anaconda3/envs/gluon/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 3885, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype, **kwargs)
  File "<string>", line 34, in _zeros
  File "/home/qbzhao/anaconda3/envs/gluon/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/home/qbzhao/anaconda3/envs/gluon/lib/python3.6/site-packages/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Invalid Parameter format for shape expect Shape(tuple) but value='
[[[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]]]
<NDArray 1x3x224x224 @cpu(0)>', in operator _zeros(name="", dtype="float32", ctx="cpu(0)", shape="
[[[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]]]
<NDArray 1x3x224x224 @cpu(0)>")

**Comment by hey-yahei** [comment]
你好，
麻烦重新clone最新的代码再试试。
在早前的版本中count_ops是接收一个input_shape的，但后来改成接收一个具体的ndarray，你这里的报错很可能是使用了早前的源码和最新的tests代码。
